name: build-deploy-prerelease

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: '5.0.x'
        config-file: nuget.config
        source-url: https://nuget.pkg.github.com/Buerkert/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build with dotnet
      run: dotnet build -c Release --version-suffix build.${{ github.run_number }}
    - name: Run unit tests
      run: dotnet test
    - name: Push generated package to GitHub registry
      run: dotnet nuget push KeraLua\bin\Release\Buerkert.KeraLua.*.nupkg
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: KeraLua
        path: KeraLua\bin\Release\*nupkg
